name: Build Pipeline

#forziamo l'uso di Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./roman-number

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Java JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilazione
        run: mvn clean compile

      - name: Esecuzione dei test
        run: mvn test

      - name: Analisi statica del codice (Checkstyle)
        run: mvn package -DskipTests #usiamo questo parametro per soddisfare il requisito della consegna "distinguere facilmente la causa del fallimento"

      - name: Calcolo code coverage e invio a Coveralls
        run: mvn coveralls:report -DrepoToken=${{ secrets.COVERALLS_TOKEN }}